version: '3.8'

services:
  api:
    build: .
    container_name: simple-api
    restart: unless-stopped
    volumes:
      - ./todos.db:/app/todos.db
    environment:
      - PORT=4000
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network

networks:
  app-network:
